version: '2.4'

services:
  pipeline:
    build: .
    container_name: nlp_data_pipeline
    volumes:
      - pipeline_data:/app/data
      - ./data_preparation:/app/data_preparation
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    mem_limit: 8g        # Increased from 4g
    mem_reservation: 4g   # Increased from 2g
    shm_size: 4g         # Increased from 2g

volumes:
  pipeline_data: